### ISSUE TITLE
stylelint 6.9.0版本

### ISSUE THREAD

**Issue by small-joker** [fisker/fis3-lint-stylelint#2]
你好， 
fis3-lint-stylelint只能基于stylelint 6.9.0版本吗， 
stylelint 6.9.0版本 没有
media-feature-name-case
declaration-block-no-redundant-longhand-properties
font-family-no-duplicate-names这三项，

**Comment by fisker** [comment]
发了个新版，更新到 ^7.0 了

不过这次主要是重写了下流程。

因为我自己使用的某些插件不支持node 4+，而stylelint 不再支持 node 0.12，我可能还会再改回旧版。
